---
# https://tecadmin.net/how-to-install-go-on-ubuntu-20-04/
- hosts: sg-vm
  # remote_user: root
  tasks:
    - name: test conn
      ping: 

    - name: Record time
      shell: "date '+%s'"
      register: time_before_reload

    # - name: curl Google
    #   uri: 
    #     url: https://www.google.com/
    #     method: HEAD
    
    - name: Get Nginx up time
      uri: 
        url: "http://10.129.98.209:9111/get_up_time" 
        method: "GET"
        return_content: yes
      register: curl_result

    - set_fact: 
        worker_up_time: "{{ curl_result.content.split(\"\n\")[0] }}"

    - name: Check Nginx up time
      fail:
        msg: "Nginx reload failed. Worker start time: {{ worker_up_time }}"
      when: worker_up_time < time_before_reload.stdout

    - name: Debug1
      debug:
        msg: "{{ time_before_reload.stdout }}"

    - name: Debug2
      debug:
        msg: "{{ worker_up_time }}"
